# Generated by Django 3.0.1 on 2019-12-26 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('participant', 'Участник'), ('approving', 'Ожидает получения статуса автора'), ('author', 'Автор'), ('tech_sec', 'Технический секретарь'), ('sci_sec', 'Учёный секретарь'), ('head', 'Руководитель секции')], default='participant', max_length=255),
            preserve_default=False,
        ),
    ]
