# Generated by Django 3.0.1 on 2019-12-26 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191226_1918'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_authorapprovalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorapprovalrequest',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='authorapprovalrequest',
            name='cover_letter',
            field=models.TextField(verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='authorapprovalrequest',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('participant', 'Участник'), ('approving', 'Ожидает получения статуса автора'), ('author', 'Автор'), ('tech_sec', 'Технический секретарь'), ('sci_sec', 'Учёный секретарь'), ('head', 'Руководитель секции')], max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
