# Generated by Django 3.0.1 on 2019-12-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191226_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorapprovalrequest',
            options={'verbose_name': 'Запрос статуса автора', 'verbose_name_plural': 'Запросы статуса автора'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
