# Generated by Django 3.0.1 on 2020-01-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191227_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorapprovalrequest',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
