# Generated by Django 3.0.1 on 2019-12-26 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_authorapprovalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='status',
        ),
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MaterialApprovalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_to', models.TextField(choices=[('tech_sec', 'Техническому секретарю (Ожидает проверки оформления)'), ('sci_sec', 'Учёному секретарю (Ожидает проверки на соответствие тематике)'), ('head', 'Руководителю секции (Ожидает подтверждения от руководителя секции)')], max_length=255)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Material')),
            ],
        ),
    ]
