# Generated by Django 3.0.1 on 2019-12-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191226_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorApprovalRequest',
        ),
    ]
