# Generated by Django 3.0.1 on 2019-12-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_delete_authorapprovalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialapprovalrequest',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.Material', verbose_name='Материал'),
        ),
    ]
