# Generated by Django 3.0.1 on 2019-12-26 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_auto_20191226_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='material',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='material',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='material',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=75, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='materialapprovalrequest',
            name='assigned_to',
            field=models.TextField(choices=[('tech_sec', 'Техническому секретарю (Ожидает проверки оформления)'), ('sci_sec', 'Учёному секретарю (Ожидает проверки на соответствие тематике)'), ('head', 'Руководителю секции (Ожидает подтверждения от руководителя секции)')], max_length=255, verbose_name='Назначен'),
        ),
        migrations.AlterField(
            model_name='materialapprovalrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='materialapprovalrequest',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='section',
            name='head',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель секции'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
