# Generated by Django 3.0.1 on 2019-12-28 23:22

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20191226_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='content',
        ),
        migrations.RemoveField(
            model_name='material',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='material',
            name='last_update',
        ),
        migrations.AddField(
            model_name='material',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=main_app.models.upload_path, verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='material',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to=main_app.models.upload_path, verbose_name='Презентация'),
        ),
    ]
