# Generated by Django 3.0.1 on 2019-12-29 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20191228_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('tech_sec', 'Проверяется на оформление тех. секретарем секции'), ('sci_sec', 'Проверяются тезисы учёным секретарем секции'), ('head', 'Ожидает подтверждения от руководителя секции'), ('approved', 'Материал подтвержден. Ждем Вас на конференции :)')], default=django.utils.timezone.now, max_length=255, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MaterialApprovalRequest',
        ),
    ]
