# Generated by Django 3.0.1 on 2020-01-04 03:11

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20191229_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='document',
            field=models.FileField(null=True, upload_to=main_app.models.upload_path, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='material',
            name='presentation',
            field=models.FileField(null=True, upload_to=main_app.models.upload_path, verbose_name='Презентация'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('tech_sec', 'Проверка оформления'), ('sci_sec', 'Проверка тезисов'), ('head', 'Ожидает подтверждения'), ('approved', 'Материал подтвержден')], max_length=255, verbose_name='Статус'),
        ),
    ]
